motherboards = [
    {
        "manufacturer": "安擎",
        "cpu_model": "Intel 4210R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 20,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "AMD 7352",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "2.3 GHz",
        "max_cpu": 1,
        "max_mem": 8,
        "max_sata_hard": 8,
        "max_nvme_hard": 2,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "Intel 4314",
        "cpu_architecture": "x86_64",
        "cpu_threads": 32,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "AMD 7352",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "2.3 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "Intel 6240R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "AMD 7453",
        "cpu_architecture": "x86_64",
        "cpu_threads": 56,
        "cpu_frequency": "2.75 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "Intel 6226R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 32,
        "cpu_frequency": "2.9 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "AMD 7443",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "2.85 GHz",
        "max_cpu": 1,
        "max_mem": 8,
        "max_sata_hard": 8,
        "max_nvme_hard": 2,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "Intel 6248R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "3.0 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "安擎",
        "cpu_model": "AMD 7313",
        "cpu_architecture": "x86_64",
        "cpu_threads": 32,
        "cpu_frequency": "3.0 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 12,
        "max_nvme_hard": 6,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "Intel 4210R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 20,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 16,
        "max_sata_hard": 6,
        "max_nvme_hard": 2,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "AMD 7402",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "2.8 GHz",
        "max_cpu": 1,
        "max_mem": 8,
        "max_sata_hard": 6,
        "max_nvme_hard": 2,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "Intel 4314",
        "cpu_architecture": "x86_64",
        "cpu_threads": 32,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 24,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "AMD 7352",
        "cpu_architecture": "x86_64",
        "cpu_threads": 64,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 1,
        "max_mem": 32,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "Intel 6240R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 24,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "AMD 7532",
        "cpu_architecture": "x86_64",
        "cpu_threads": 64,
        "cpu_frequency": "2.4 GHz",
        "max_cpu": 2,
        "max_mem": 32,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "Intel 6226R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 32,
        "cpu_frequency": "2.9 GHz",
        "max_cpu": 2,
        "max_mem": 24,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "AMD 7542",
        "cpu_architecture": "x86_64",
        "cpu_threads": 64,
        "cpu_frequency": "2.9 GHz",
        "max_cpu": 1,
        "max_mem": 16,
        "max_sata_hard": 6,
        "max_nvme_hard": 2,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "Intel 6248R",
        "cpu_architecture": "x86_64",
        "cpu_threads": 48,
        "cpu_frequency": "3.0 GHz",
        "max_cpu": 2,
        "max_mem": 24,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
    {
        "manufacturer": "国鑫",
        "cpu_model": "AMD 7542",
        "cpu_architecture": "x86_64",
        "cpu_threads": 64,
        "cpu_frequency": "2.9 GHz",
        "max_cpu": 1,
        "max_mem": 32,
        "max_sata_hard": 10,
        "max_nvme_hard": 4,
    },
]

memorys = [
    {"capacity_gb": 32},
    {"capacity_gb": 64},
    {"capacity_gb": 128},
]

disks = [
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 4},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 6},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 8},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 10},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 12},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 14},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 16},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 18},
    {"interface_type": "SATA", "is_hdd": 1, "capacity_tb": 20},
    {"interface_type": "NVMe", "is_hdd": 1, "capacity_tb": 0.96},
    {"interface_type": "NVMe", "is_hdd": 1, "capacity_tb": 1.92},
    {"interface_type": "NVMe", "is_hdd": 1, "capacity_tb": 3.84},
]
