"""empty message

Revision ID: 22563dae26aa
Revises: 865dd6223abb
Create Date: 2023-08-15 09:38:56.115854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22563dae26aa'
down_revision = '865dd6223abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu_motherboard', schema=None) as batch_op:
        batch_op.alter_column('cpu_model',
               existing_type=mysql.VARCHAR(length=32),
               comment='cpu型号',
               existing_nullable=False)
        batch_op.alter_column('architecture',
               existing_type=mysql.VARCHAR(length=32),
               comment='cpu架构,x86_64,aarch64',
               existing_nullable=False)
        batch_op.alter_column('cores',
               existing_type=mysql.INTEGER(display_width=11),
               comment='cpu核心数',
               existing_nullable=False)
        batch_op.alter_column('threads',
               existing_type=mysql.INTEGER(display_width=11),
               comment='cpu线程数',
               existing_nullable=False)
        batch_op.alter_column('frequency',
               existing_type=mysql.VARCHAR(length=16),
               comment='cpu主频',
               existing_nullable=False)
        batch_op.alter_column('max_mem_slot',
               existing_type=mysql.INTEGER(display_width=11),
               comment='最大内存插槽数',
               existing_nullable=False)
        batch_op.alter_column('max_hard_slot',
               existing_type=mysql.INTEGER(display_width=11),
               comment='最大硬盘插槽数',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment='价格',
               existing_nullable=False)

    with op.batch_alter_table('hard', schema=None) as batch_op:
        batch_op.alter_column('hard_model',
               existing_type=mysql.VARCHAR(length=32),
               comment='硬盘型号',
               existing_nullable=False)
        batch_op.alter_column('interface_type',
               existing_type=mysql.VARCHAR(length=16),
               comment='接口类型',
               existing_nullable=False)
        batch_op.alter_column('ishdd',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否是机械',
               existing_nullable=False)
        batch_op.alter_column('capacity',
               existing_type=mysql.INTEGER(display_width=11),
               comment='硬盘容量',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment='价格',
               existing_nullable=False)

    with op.batch_alter_table('mem', schema=None) as batch_op:
        batch_op.alter_column('mem_model',
               existing_type=mysql.VARCHAR(length=32),
               comment='价格',
               existing_nullable=False)
        batch_op.alter_column('mem_frequency',
               existing_type=mysql.VARCHAR(length=16),
               comment='内存主频',
               existing_nullable=False)
        batch_op.alter_column('capacity',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内存容量',
               existing_nullable=False)
        batch_op.alter_column('mem_type',
               existing_type=mysql.VARCHAR(length=8),
               comment='内存类型, ddr3/ddr4',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment='价格',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mem', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='价格',
               existing_nullable=False)
        batch_op.alter_column('mem_type',
               existing_type=mysql.VARCHAR(length=8),
               comment=None,
               existing_comment='内存类型, ddr3/ddr4',
               existing_nullable=False)
        batch_op.alter_column('capacity',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='内存容量',
               existing_nullable=False)
        batch_op.alter_column('mem_frequency',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='内存主频',
               existing_nullable=False)
        batch_op.alter_column('mem_model',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='价格',
               existing_nullable=False)

    with op.batch_alter_table('hard', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='价格',
               existing_nullable=False)
        batch_op.alter_column('capacity',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='硬盘容量',
               existing_nullable=False)
        batch_op.alter_column('ishdd',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否是机械',
               existing_nullable=False)
        batch_op.alter_column('interface_type',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='接口类型',
               existing_nullable=False)
        batch_op.alter_column('hard_model',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='硬盘型号',
               existing_nullable=False)

    with op.batch_alter_table('cpu_motherboard', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='价格',
               existing_nullable=False)
        batch_op.alter_column('max_hard_slot',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='最大硬盘插槽数',
               existing_nullable=False)
        batch_op.alter_column('max_mem_slot',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='最大内存插槽数',
               existing_nullable=False)
        batch_op.alter_column('frequency',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='cpu主频',
               existing_nullable=False)
        batch_op.alter_column('threads',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='cpu线程数',
               existing_nullable=False)
        batch_op.alter_column('cores',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='cpu核心数',
               existing_nullable=False)
        batch_op.alter_column('architecture',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='cpu架构,x86_64,aarch64',
               existing_nullable=False)
        batch_op.alter_column('cpu_model',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='cpu型号',
               existing_nullable=False)

    # ### end Alembic commands ###
