"""empty message

Revision ID: 8070ed38d642
Revises: 
Create Date: 2023-09-06 19:17:22.194925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8070ed38d642'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_type', sa.String(length=16), nullable=False, comment='接口类型'),
    sa.Column('is_hdd', sa.Integer(), nullable=False, comment='是否是机械硬盘'),
    sa.Column('capacity_gb', sa.Integer(), nullable=False, comment='硬盘容量,单位GB'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False, comment='内存容量,单位GB'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motherboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False, comment='主板制造商:安擎,国鑫'),
    sa.Column('cpu_model', sa.String(length=32), nullable=False, comment='CPU型号'),
    sa.Column('cpu_architecture', sa.String(length=32), nullable=False, comment='CPU架构, x86_64, aarch64'),
    sa.Column('cpu_threads', sa.Integer(), nullable=False, comment='CPU线程数'),
    sa.Column('cpu_frequency', sa.String(length=16), nullable=False, comment='CPU主频'),
    sa.Column('max_cpu', sa.Integer(), nullable=False, comment='最大CPU插槽数'),
    sa.Column('max_mem', sa.Integer(), nullable=False, comment='最大内存插槽数'),
    sa.Column('max_sata_hard', sa.Integer(), nullable=False, comment='最大SATA硬盘插槽数'),
    sa.Column('max_nvme_hard', sa.Integer(), nullable=False, comment='最大NVME硬盘插槽数'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motherboard')
    op.drop_table('memory')
    op.drop_table('disk')
    # ### end Alembic commands ###
