"""empty message

Revision ID: 865dd6223abb
Revises: 19d4b07f4716
Create Date: 2023-08-15 09:21:10.214438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '865dd6223abb'
down_revision = '19d4b07f4716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu_motherboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('architecture', sa.String(length=32), nullable=False))
        batch_op.drop_column('max_mem_slot1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu_motherboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_mem_slot1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('architecture')

    # ### end Alembic commands ###
