"""empty message

Revision ID: cc0443affc3f
Revises: 22563dae26aa
Create Date: 2023-08-15 10:23:21.006594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc0443affc3f'
down_revision = '22563dae26aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hard_model', sa.String(length=32), nullable=False, comment='硬盘型号'),
    sa.Column('interface_type', sa.String(length=16), nullable=False, comment='接口类型'),
    sa.Column('ishdd', sa.Boolean(), nullable=False, comment='是否是机械'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='硬盘容量'),
    sa.Column('price', sa.Float(), nullable=False, comment='价格'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hard_model')
    )
    with op.batch_alter_table('hard', schema=None) as batch_op:
        batch_op.drop_index('hard_model')

    op.drop_table('hard')
    with op.batch_alter_table('cpu_motherboard', schema=None) as batch_op:
        batch_op.drop_column('cores')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu_motherboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cores', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='cpu核心数'))

    op.create_table('hard',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hard_model', mysql.VARCHAR(length=32), nullable=False, comment='硬盘型号'),
    sa.Column('interface_type', mysql.VARCHAR(length=16), nullable=False, comment='接口类型'),
    sa.Column('ishdd', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否是机械'),
    sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='硬盘容量'),
    sa.Column('price', mysql.FLOAT(), nullable=False, comment='价格'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hard', schema=None) as batch_op:
        batch_op.create_index('hard_model', ['hard_model'], unique=False)

    op.drop_table('disk')
    # ### end Alembic commands ###
